name: ci

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: environment setup
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run test
        run: bundle exec rake

  build:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Package Info
        id: package_info
        uses: ./.github/actions/package_info

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          tags: ${{ steps.package_info.outputs.name }}:${{ github.sha }}
          file: ./Dockerfile
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            APP_NAME=${{ steps.package_info.outputs.name }}
            NODE_AUTH_TOKEN=${{ secrets.EL_B2C_BOT_TOKEN_PACKAGE_WRITER }}

