# Generated and managed by GitOps. Don't edit this file manually
name: ecr-cn

on:
  workflow_dispatch:

jobs:
  cd:
    name: ecr-cn
    runs-on: ubuntu-latest

    steps:
      - name: pull code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.EL_ECR_PUSHER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.EL_ECR_PUSHER_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 479788333518

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.EL_ECR_PUSHER_AWS_ACCESS_KEY_ID_CHINA }}
          aws-secret-access-key: ${{ secrets.EL_ECR_PUSHER_AWS_SECRET_ACCESS_KEY_CHINA }}
          aws-region: cn-northwest-1

      - name: Login to Amazon ECR
        id: login-ecr-china
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 142732145294

      - name: package information
        id: package_info
        uses: ./.github/actions/package_info
      
      - name: docker information
        id: docker_info
        uses: ./.github/actions/docker_info
        with:
          aws_registry: ${{ steps.login-ecr.outputs.registry }}
          owner: ${{ steps.package_info.outputs.owner }}
          namespace: ${{ steps.package_info.outputs.namespace }}
          name: ${{ steps.package_info.outputs.name }}
          version: ${{ steps.package_info.outputs.version }}

      - name: docker publish
        env:
          DOCKER_REGISTRY_AWS: ${{ steps.package_info.outputs.docker_registry_aws }}
        run: |
          docker pull ${DOCKER_REGISTRY_AWS}
          docker tag ${DOCKER_REGISTRY_AWS} ${{ steps.login-ecr-china.outputs.registry }}/$(echo ${DOCKER_REGISTRY_AWS} | cut -d/ -f2-)
          docker push ${{ steps.login-ecr-china.outputs.registry }}/$(echo ${DOCKER_REGISTRY_AWS} | cut -d/ -f2-)
